### ISSUE TITLE
Sorting data with decimals

### ISSUE THREAD

**Issue by jesseokeya** [Lagbana/DataPlayground#2]
### Major Issue
-  when filtering through the data and sorting if a decimal is in the search criteria an error occurs
- find the error and resolve the issue

```python
    # filter the data by Age and further filter it by ages 20 to 70
    search_criteria = 'Balance'
    search_value = [900, 7000]
    # return an array of dictionaries of all data that meets the filter
    # criterias
    search_field = sorted_data.search(search_criteria, search_value)
```

```
Traceback (most recent call last):
  File "index.py", line 68, in <module>
    main()
  File "index.py", line 51, in main
    get_minimum_age = sorted_data.get_minimum_value('Age', search_field)
  File "/Users/jesseokeya/Documents/DataPlayground/src/sort.py", line 101, in get_minimum_value
    minimum_num = int(sorted_data[0][search_field])
IndexError: list index out of range
```

**Comment by jesseokeya** [comment]
Issue Solved!!
